### ISSUE TITLE
ArcWelderConsole large gaps in walls

### ISSUE THREAD

**Issue by ghost** [FormerLurker/ArcWelderPlugin#100]
using ArcWelderConsole.exe on win8.1pro.

Been working flawlessly, except for some large cylindrical models ( like large pots ).
The walls ( inner and outer ) have gaps about 10mm wide, 4 per circumference.
I am guessing that ArcWelder is splitting the circular shape in to 4 sections, and the gap appears between sections.
Diameter of the models is between 150 and 210 mm.
Infill in the areas is still being printed.
Seems that it only appears where the wall of the pot is vertical or very close to vertical.

![Screenshot_5](https://user-images.githubusercontent.com/12676182/102578684-64fde400-4103-11eb-975c-b74824d71318.jpg)

**Comment by FormerLurker** [comment]
Interesting.  Can you post the before and after gcode please?  I am working on another issue, and i think they may be related.

**Comment by ghost** [comment]
Hi
Attached zip of the 2 files, and also batch file output from ArcWelderConsole.exe
Not isolated to a single model. I am doing a range of these and happening on different models.

Also, please can you point me to where I find the ArcWelderConsole.exe file ? Can't see it anywhere on github.

Regards
Dave

[ArcOutput.txt](https://github.com/FormerLurker/ArcWelderPlugin/files/5713922/ArcOutput.txt)
[Rounded Large.zip](https://github.com/FormerLurker/ArcWelderPlugin/files/5713914/Rounded.Large.zip)

**Comment by ghost** [comment]
ok. I found the exe in the ArcWelderLib

**Comment by FormerLurker** [comment]
Awesome.  There could be a few issues with the new binaries.  Keep your eyes peeled for an update to the artifacts.

**Comment by ghost** [comment]
that would be the file Windows-MSVC.zip in the ArcWelderLib ?

**Comment by FormerLurker** [comment]
Yes.  I need to clean up the artifacts, just haven't had time.  No need for an msvc and mingw version, and mingw is broken (I would need to add static linking, but why bother when I can just remove it, lol)

**Comment by ghost** [comment]
> Yes. I need to clean up the artifacts, just haven't had time. No need for an msvc and mingw version, and mingw is broken (I would need to add static linking, but why bother when I can just remove it, lol)

to a non-technical person, that is as 'clear as mud' :)

**Comment by FormerLurker** [comment]
@DaveZA, sorry it's taken me so long to work my way back to your issue (work is always nuts right before the new year).  I tried looking at your zip file, and it was flagged by google as containing malware.  I ran my anti-virus on it, and it said the same thing, so I'm not going to open it.  I recommend you scan your PC.

Can you post the before and after on gist.github.com instead and drop a link in here?  That should be just fine.

**Comment by ghost** [comment]
> 
> 
> @DaveZA, sorry it's taken me so long to work my way back to your issue (work is always nuts right before the new year). I tried looking at your zip file, and it was flagged by google as containing malware. I ran my anti-virus on it, and it said the same thing, so I'm not going to open it. I recommend you scan your PC.
> 
> Can you post the before and after on gist.github.com instead and drop a link in here? That should be just fine.

very odd. 
I also downloaded the zip file and got the same warnings. 
I have already deleted the files from my PC a few days back.
This will have to wait until I have a new model that presents the same problems, although I have already decided to upgrade the printer to an SKR 1.4 Turbo 32 bit board in the first week of the new year, so there's also a good chance that this will no longer be an issue

**Comment by FormerLurker** [comment]
Ok, that is fine!  Let me know how it goes!

**Comment by FormerLurker** [comment]
@DaveZA, I'm going to close this issue for now, but if you continue to have problems with the new board I will reopen it.  Thanks!
