### ISSUE TITLE
Possible gcode conversion problem.

### ISSUE THREAD

**Issue by Prickly-Pear** [FormerLurker/ArcWelderPlugin#11]
I have converted a large gcode file using Arc Welder. The file size was reduced from 106.6MB to 36.6MB and when viewed in NC Viewer, it looked ok with no strange rapid movements.
Partway through, the print failed at layer 371 (or nearby) with a slight shift in the y-axis, about +2.5mm. The original code file printed just fine (printed from SD card, of course) and it was printed immediately after the failed print without needing to clean nozzle or anything else, thus ruling out any filament clogs or similar issues.

Original file on the left and converted file on the right.
![IMG_4651](https://user-images.githubusercontent.com/62167540/80579542-93805f00-8a4d-11ea-9f9e-95081485e46c.JPG)

Close-up picture shows the y-axis shift and there is also plenty of blobbing and what-not.
![IMG_4652 copy](https://user-images.githubusercontent.com/62167540/80581197-291cee00-8a50-11ea-8c80-0c8d15c95abf.jpg)
![IMG_4653 copy](https://user-images.githubusercontent.com/62167540/80581526-9b8dce00-8a50-11ea-9f37-315b1d50ef69.jpg)
![IMG_4656 copy](https://user-images.githubusercontent.com/62167540/80582392-f96ee580-8a51-11ea-99d3-e453a7917b6f.jpg)

There is also an interesting effect in that the infill stopped printing, as can be seen in this picture:
![IMG_4654 copy](https://user-images.githubusercontent.com/62167540/80582476-202d1c00-8a52-11ea-98f4-6e3a3f99bcbe.jpg)

I have inspected the converted gcode file but I cannot see anything strange. However, I am not an expert and I could easily have missed something. 

Link to converted gcode file: https://drive.google.com/file/d/12L_ssGwVAWxceoSo1AKa4dLeFE0VpFoJ/view?usp=sharing
Link to original gcode file: https://drive.google.com/file/d/17ZgFxpv9w-4E8iQ7mXbSPKGWo8V_GknQ/view?usp=sharing

Printing Info:
RaspberryPi model **1B** with OctoPrint 1.4.0 on OctoPi 0.16.0
Slicer: Cura v4.5
Ender 3 Pro with BTT SKR mini E3 v1.2 and BLTouch
0.2 mm layer height with 0.4 mm nozzle
50 mm/s, 3 walls @ 0.4mm, infill 10%
max resolution 0.5mm, max deviation 0.05mm, relative extrusion
MM_PER_ARC_SEGMENT is 0.05mm

**Comment by FormerLurker** [comment]
Thanks for posting this.  I will start investigating this as well as your mac/windows installation issues (I think I understand both of those, so it's just a matter of patching and testing).

**Comment by FormerLurker** [comment]
This too should be solved.  I have run your super massive gcode through ArcWelder, and it looks like it is fixed.  I found that arcs with a radius that is too large cause overflow problems, so there is now a reasonable limit on the radius of large arcs.

**Comment by FormerLurker** [comment]
FYI, this file has proved to be extremely useful for testing arc-welder in general.  It contains a lot of tricky situations, and I wanted to thank you for sharing it!  Going to close this out since you can be sure that any release of arc welder will be tested with this file :)
