### ISSUE TITLE
Arc welder not creating arcs

### ISSUE THREAD

**Issue by KenLucke** [FormerLurker/ArcWelderPlugin#117]
Should not AW be turning these segments into arcs?

<img width="522" alt="image" src="https://user-images.githubusercontent.com/57936294/104135808-17157e00-5347-11eb-9b10-4b33adb1761b.png">

<img width="860" alt="image" src="https://user-images.githubusercontent.com/57936294/104135821-2dbbd500-5347-11eb-8777-247ab74a5446.png">

**Comment by FormerLurker** [comment]
I need to see the source and target gcode to determine this.  It also wouldn't hurt to see your arcwelder settings.

**Comment by KenLucke** [comment]
Settings are default

<img width="684" alt="image" src="https://user-images.githubusercontent.com/57936294/104137922-4206ce80-5355-11eb-8391-52bf5fd844d7.png">

Here are the files, before & after:
https://www.dropbox.com/s/8odecip8le4zssv/Crab%20Float.zip

**Comment by KenLucke** [comment]
This seems to have solved itself, somehow.  See #122 .
(ain't computers fun?)

You can close it if you feel comfortable doing so,

**Comment by FormerLurker** [comment]
@KenLucke, I'm going to leave this up for a bit since I would like to run the numbers on the bit you pointed out just as a sanity check.  I've been tweaking the algorithm a lot (it's a never ending process), and I think it's a worth seeing if I can explain this.

You've posted a lot in here, and i wanted to thank you for being so engaged!  I appreciate it.

**Comment by FormerLurker** [comment]
Hey, going to close this since I can't seem to get to the source files anymore.  Let's call it a fluke :)

**Comment by KenLucke** [comment]
Damn, I switched to a new laptop due to my old one needing a keyboard replacement (almost all the keys were doooooubbble and tripppppppple tapppppppping and I had to fix 3 out of 5 words I'd type, which was highly annoying) and was doing some cleaning up of my local dropbox space and deleted them.  I had ass/u/med you had downloaded them.

I agree with calling it a fluke unless it pops up again.
