### ISSUE TITLE
No issue, just an example

### ISSUE THREAD

**Issue by KenLucke** [FormerLurker/ArcWelderPlugin#122]
Left: w/Arc Welder (done under Octoprint... the Cura extension always crashes for me)
Right w/o Arc Welder

![IMG_1347](https://user-images.githubusercontent.com/57936294/104759797-4ba58300-5715-11eb-9ac6-1da5069fa99c.JPG)

**Comment by FormerLurker** [comment]
Wow!  Thank you for posting this :)  Would you mind posting your settings?  Also, can I use this image?

**Comment by KenLucke** [comment]
> Wow! Thank you for posting this :) Would you mind posting your settings? Also, can I use this image?

Slicer or AW settings?  AW is just default.

**Comment by FormerLurker** [comment]
Just defaults!  That is nuts.

**Comment by KenLucke** [comment]
> Just defaults! That is nuts.

Yeah, I'm fairly impressed.

**Comment by FormerLurker** [comment]
Ok, going to close this out since I'm doing some housekeeping, but I am going to save this image and use it in the plugin repo when I drop the next release (that is if I can ever fix all the bugs you find, LOL)
