### ISSUE TITLE
Processed gcode has detrimental effect on small features using default parameter values

### ISSUE THREAD

**Issue by brettvitaz** [FormerLurker/ArcWelderPlugin#129]
Thanks for the plugin! I have just started using it and am having some issue with small circular features.

I have not adjusted the parameter values from default.
Resolution = 0.05mm

The result of the processed gcode causes deformed posts on prints. Here is an example of unprocessed and processed output:
![IMG_0106](https://user-images.githubusercontent.com/7563757/105614513-be9aa380-5d7e-11eb-92ec-6ff84b19398d.png)

Here is the gcode used:
[gcode.zip](https://github.com/FormerLurker/ArcWelderPlugin/files/5861072/gcode.zip)

Printer: Prusa MK3S
Slicer: PrusaSlicer 2.3

Is this something I should fix by adjusting the resolution, or is this some kind of issue that I should expect the plugin to handle?

**Comment by FormerLurker** [comment]
Well, this is firmware related.  I have posted a pull request to fix this in the mk2/mk3 firmware github.  However, i wouldn't assume it will be accepted.  I have added a new feature to the devel Branch to deal with this shortcoming called firmware compensation (in addition to a bunch of other things).  Would you be willing to give it a go and see if it solves your issue?

**Comment by brettvitaz** [comment]
Sure, I'll try out the changes. I have installed the plugin from the Devel branch and will post an update with the results.

**Comment by FormerLurker** [comment]
excellent, thanks!  I think the default firmware compensation settings should work well for you:

![image](https://user-images.githubusercontent.com/33363128/105638344-c5392180-5e37-11eb-8c69-2d29802a274b.png)

Also, I'm interested in what the firmware checker says about your printer:

![image](https://user-images.githubusercontent.com/33363128/105638362-d84bf180-5e37-11eb-9e1f-538529f0216e.png)

**Comment by brettvitaz** [comment]
I have set the firmware compensation to your suggested values. The output is much improved and is now similar to the unprocessed version. Thank you for your help!

Here is the reported Firmware Compatibility:
![Screen Shot 2021-01-24 at 10 19 53 AM](https://user-images.githubusercontent.com/7563757/105639583-062c3880-5e2e-11eb-8082-a6a1916c6e84.png)

**Comment by FormerLurker** [comment]
You may want to consider posting an issue to the PrusaFirmware repository.  I think it would be good if they knew how many people are affected by the shortcomings of their current g2/g3 implementation.  If enough people are having problems like your, perhaps some changes will be made?

**Comment by brettvitaz** [comment]
I will post an issue with PrusaFirmware. Does the same issue exist in Marlin? I have some Ender 3 printers running the latest Marlin release. I can check those some time next week.

**Comment by FormerLurker** [comment]
@brettvitaz, the latest version of marlin has much enhanced arc interpolation capabilities.  Depending on the settings, you won't have any issues on the latest marlin.

**Comment by brettvitaz** [comment]
Great! Thanks again.

**Comment by brettvitaz** [comment]
Using the settings you suggested, I printed a part this morning and noticed significant straightening of the arc segments.

I'm not sure if they show up well in this photo, but here are the results:
![IMG_0107](https://user-images.githubusercontent.com/7563757/105646371-76e64b80-5e54-11eb-92d2-161718e63b18.png)

**Comment by FormerLurker** [comment]
You can increase min arc segments.  Marlin's default is 24, but you won't get much, if any, compression like that.  The firmware compensation is a hack, unfortunately, so the only real fix is to update the firmware.

**Comment by FormerLurker** [comment]
When i said you won't get much compression, i meant for small arcs, like your example.  Large pieces will perform better.
