### ISSUE TITLE
[FR] Automatically start print after AW is done processing

### ISSUE THREAD

**Issue by nuxy69** [FormerLurker/ArcWelderPlugin#186]
Before AW I was using the checkmark in PrusaSlicer to automatically start the print after upload. So that I dont have to go into OctoPrint to start the print. 
Now with AW I can't use that checkmark anymore, so I do have to go in OctoPrint to select the .aw.gcode and print that. 
A setting would be great that after AW is done processing that file will be automatically chosen to start printing.

**Comment by FormerLurker** [comment]
Check the 'Discussions' tab for instructions on how to install the latest beta.  This feature has already been implemented :)

**Comment by nuxy69** [comment]
Allright! Missed that one! Thanks!
