### ISSUE TITLE
"mm_per_arc_segment" setting not present

### ISSUE THREAD

**Issue by Eliminateur** [FormerLurker/ArcWelderPlugin#192]
In the octoprint plugin there's no way to configure mm_per_arc_segment

**Comment by FormerLurker** [comment]
I see this is closed, but I did add something I'm calling 'Firmware Compensation' that is available in the beta for people running Marlin 1 or a fork.  See the discussions tab above for instructions on how to install, and be sure to read the instructions within the settings.

Anyway, good luck!

**Comment by Eliminateur** [comment]
i closed it because i realized that setting is ONLY if you need firmware compensation(documentation is kind of ambiguous about it).

For example, if in my firmware i change the mm per arc segment to 0.1, ¿do i need to set that in arc welder?

**Comment by FormerLurker** [comment]
Here is the context help for the firmware compensation enabled setting:

![image](https://user-images.githubusercontent.com/33363128/115274393-366e3500-a106-11eb-961e-6089b829dde3.png)

Let me know how I can improve that to make it more clear.

> For example, if in my firmware i change the mm per arc segment to 0.1, ¿do i need to set that in arc welder?

You only need firmware compensation if your firmware ONLY has the mm_per_arc_segment setting (and not, say, minimum_arc_segments, or some of the other enhanced arc generation settings) AND you have issues where arcs of a small radius are coming out flat.  0.1mm segments is very small, so you probably won't notice the flattening at all.

**Comment by Eliminateur** [comment]
perfect, so for marlin 2.0.2 that has both MM_PER_ARC_SEGMENT and MIN_ARC_SEGMENTS defined and configured in the config files then i should not enable anything on arc welder

**Comment by FormerLurker** [comment]
That is correct!

**Comment by Eliminateur** [comment]
Perfect,
that would be a good addendum to the documentation on fw compensation:
If you're running Marlin 2.0.x and have these two values set, then you don't need to set FW compensation or configure those two values(cura plugin has no fw compensation checkbox, only those values to edit or reset)
