### ISSUE TITLE
When uploading multiple files to octoprint, the completed AW stats page is not visible

### ISSUE THREAD

**Issue by jurassic73** [FormerLurker/ArcWelderPlugin#199]
I uploaded two files (drag and drop in one action) and both items were processed by AW however only the last one processed displayed the 'page icon' in the directory to then be able to see it's stats.  The other processed file with aw in the filename still had the two arrows icon.

Excellent plug-in BTW!  Amazing work.

**Comment by FormerLurker** [comment]
Are you using the stable version or the latest development version?  A snapshot of the ArcWelder tab should suffice (it has the version number at the bottom including a link)

**Comment by jurassic73** [comment]
Stable as pulled in via Octoprint I believe.  Arc Welder v1.0.0+u.bb71e8f

![notes](https://user-images.githubusercontent.com/50930136/121236919-53dc9700-c84b-11eb-8630-2fb7f81e6d9c.png)

I thought after being processed, it would not be able to be welded again?

**Comment by FormerLurker** [comment]
Yeah, that's a bug I believe I fixed.  Try installing the latest beta version [using this guide](https://github.com/FormerLurker/ArcWelderPlugin/discussions/141).  FYI, I'm going to be pushing another major update soon with a bunch of fixes and enhancements.  Also, I recommend setting the max arc radius to 10000mm, as a few issues were discovered with marlin's interpolation algorithm, and that will work around them for now.  Newer versions will apply this automatically.

**Comment by jurassic73** [comment]
Thanks for looking at this.  Appreciate it and will do.

**Comment by FormerLurker** [comment]
Of course!  If the new version doesn't work, reopen the issue and I'll double check the latest dev code.
