### ISSUE TITLE
Can't install recent version through plugin manager in Octoprint

### ISSUE THREAD

**Issue by reinharm1959** [FormerLurker/ArcWelderPlugin#20]

**Comment by reinharm1959** [comment]
please provide the correct link to upload the latest version via Octoprint plugin manager

**Comment by FormerLurker** [comment]
Please read the readme.md for full instructions installing latest releases, or from a specific branch.

Here is the latest release zip archive link, which can be found under the releases tab within the GitHub repo: https://github.com/FormerLurker/ArcWelderPlugin/archive/0.1.0rc1.dev4.zip

**Comment by FormerLurker** [comment]
This has been open for a while, so I'm going to go ahead and close it.  I will likely be officially publishing this via the plugin manager soon, so this won't be an issue anymore.  Thanks for participating!
