### ISSUE TITLE
option to disable automatic convert / compression

### ISSUE THREAD

**Issue by TylonHH** [FormerLurker/ArcWelderPlugin#230]
Hi,
I use the plugin [continuous print](https://plugins.octoprint.org/plugins/continuousprint/). The plugin generate gcodes to clean the bed.
In this moment your awesome plugin is converting the new gcode. Thats bad in this workflow.
So I have to disable your plugin within your menu. But then the manual compression in the file list also disappear.

So I request an option to disable the auto-compression. I still wanna use the button within the file-list.

I hope you understand what I mean.

kind regards

**Comment by FormerLurker** [comment]
Is there not an 'auto process' option in your version?  It has honestly been a long time since I looked at the master release, so maybe it isn't there.

On a positive note, even if this isn't available in your version, there is a newer version you are welcome to try.  It is packed with all kinds of goodies.  Let me know!

**Comment by TylonHH** [comment]
Shame on me: I'm on Arc-Welder (1.0.1rc1.dev2) because of the experimental feature "3D Arcs(vase mode)".
If the newest version has the vase mode too, I'll test it.

**Comment by FormerLurker** [comment]
It does, as well as travel arc support and better statistics!  I just pushed new changes last weekend.

**Comment by TylonHH** [comment]
> It does, as well as travel arc support and better statistics! I just pushed new changes last weekend.

The [latest release](https://github.com/FormerLurker/ArcWelderPlugin/releases) I see is 1.0.0 from 10/2020 and the latest RC from 11/2021
As I wrote I'm at 1.0.1rc1.dev2. I guess you mean this [RC](https://github.com/FormerLurker/ArcWelderPlugin/tree/rc/maintenance).

**Comment by FormerLurker** [comment]
No, these changes aren't in that release.  Try installing with the following url in the plugin manager (get more-> From url...): ```https://github.com/FormerLurker/ArcWelderPlugin/archive/refs/heads/rc/maintenance.zip```

**Comment by TylonHH** [comment]
yeah I did. But there I still see no "auto process" option.

**Comment by FormerLurker** [comment]
Check here:

![image](https://user-images.githubusercontent.com/33363128/165972070-0674e877-d221-49b8-b308-be494383ac55.png)

I was wrong about the label for this setting, but I think you'll get the idea.
