### ISSUE TITLE
Question about statistics after "arcing"

### ISSUE THREAD

**Issue by xeddog** [FormerLurker/ArcWelderPlugin#26]
In the attached screenshot are the stats for a T-Tex tooth I sliced, uploaded, and welded.    I get all of the stats except Points Compressed.  Is that the number of small straight moves that have been made into the given number of arcs?  In this case, 1550266 small straight move segments have been converted into 440127 arcs?  

Wayne

![image](https://user-images.githubusercontent.com/8324160/85933609-c0a28f80-b88d-11ea-833c-fe4e53bf76b2.png)

**Comment by xeddog** [comment]
And a second question - do you have any plans to support G2/G3 commands with the "P" operand for full circles???

**Comment by FormerLurker** [comment]
Yes, 1550266 points were turned into 440127 arcs.  Also, full circles are not supported because that could lead to overlap in general models.  Arcwelder will always generate semi-circles, though they may be very close to a full circle.
