### ISSUE TITLE
Klipper Supported?

### ISSUE THREAD

**Issue by DroneMang** [FormerLurker/ArcWelderPlugin#28]
Hi,

I am using Klipper, and just wondering if this plugin will work.  It looks like it will be, so perhaps a blurb could be added to the documentation for Klipper users describing what to enable etc.

So far I have found to enable the below in Klippers printer.cfg, but what should the resolution be?  It defaults to 1.  On the about tab in Octoprint, you recommend 0.1mm, does this hold for Klipper?

[gcode_arcs]
#resolution: 1.0

Also, will firmware retract and pressure advance still work as intended?  How about tool changes (done in the slicer or via macros in Klipper)?

I have had some stuttering on circles so this should be awesome!

DroneMang

**Comment by FormerLurker** [comment]
It should work as long as arcs are enabled.  Try a resolution of 0.25mm for starters.  Increase if arcs cause slowdown, but you probably have more than enough processing power to handle 0.25mm segments.

All of the other options should still work (lin advance etc), because behind the scenes klipper is generating small segments (the resolution setting) to generate the arcs.

**Comment by changedsoul** [comment]
Im sorry to bring this back up, but I am using klipper "without" octoprint.
How would I get this to convert some files.

**Comment by FormerLurker** [comment]
@changedsoul, what OS?  I have windows/linux/linux arm binaries of a command line version.

**Comment by FormerLurker** [comment]
Check [here](https://github.com/FormerLurker/ArcWelderLib/actions/runs/107579357)

I have an arm binary for raspberry pi too somewhere, but I would have to manually build it since git actions dont support that yet.  Also, IOS and Ubuntu may have issues (still ironing out the kinks there)

**Comment by changedsoul** [comment]
> @changedsoul, what OS? I have windows/linux/linux arm binaries of a command line version.

Its for a raspberry pi....what ever OS is installed on that....I think debian?

**Comment by FormerLurker** [comment]
Rasbian.  I will have yo manually compile that.  Give me a day or two and I can send it.  If you happen to have access to a windows machine you could use that in the meanwhile.

**Comment by changedsoul** [comment]
I downloaded the Linux one and ran it on my arch distro and it seem to be working nicely. I am going to compare a before and after print, but my first impressions are that just using arcs seems to have made my printer much quieter, lol. 
Very promising.

**Comment by FormerLurker** [comment]
Awesome!  Star the repos if you think they are useful.  Enjoy the app, and post any feedback or thoughts please, good or bad.

**Comment by DroneMang** [comment]
I am happy to report that this has been working great in Klipper.  I have even made the resulution smaller in Klipper, half as small as recommended as a start point, no issues.  I am printing with an SKR PRO.  

[gcode_arcs]
resolution: 0.05

**Comment by FormerLurker** [comment]
Wow!  At that resolution you should have next to no deviation at all.  Do you notice any change at all in print quality or speed?

**Comment by DroneMang** [comment]
Well I didn't really notice anything different, but the log for how the mcu
and connection is performing did seem like things were getting more taxed.
The good thing with Klipper is it will throw an error or shutdown if it
can't keep up, and it kept right on going.

**Comment by FormerLurker** [comment]
Since things appear to be going well with klipper, I'm going to go ahead and close this.  Thanks for participating!
