### ISSUE TITLE
Command line usage

### ISSUE THREAD

**Issue by furynick** [FormerLurker/ArcWelderPlugin#29]
Can you add some documentation on how to install and use ArcWelder with command line, I would like to enable it in Simplify3D post-processing.

**Comment by FormerLurker** [comment]
Wrong repo.  Check out [ArcWelderLib binaries](https://github.com/FormerLurker/ArcWelderLib/actions/runs/107579357).  Please not that it's not working properly in MacOs/Ubuntu, depending on the installed compilers.

I also have an ARM build, but I couldn't make it work in the github actions.

**Comment by FormerLurker** [comment]
This has been open for a while, so I'm going to go ahead and close this.  I hope you got the console version working!
