### ISSUE TITLE
Windows 10 Pop-Up Notifications

### ISSUE THREAD

**Issue by jneilliii** [FormerLurker/ArcWelderPlugin#3]
There is a bit of a formatting issue with this latest version in the Windows 10 Pop-Up after a file is processed.

![image](https://user-images.githubusercontent.com/5249455/80309705-b76d4780-87a4-11ea-9ebb-fb5d826f73c0.png)

It would also be nice to have this notification a configurable option (to show/not to show),

**Comment by FormerLurker** [comment]
I need to turn off desktop notification, or find a way to use a separate desktop toast for that notification.

Funny you should ask to turn it off because 3 people asked for such a pop-up (it didn't exist originally), lol.  I'm hesitant to add too many more settings, but i think i could make room for this.

Thanks for posting!

**Comment by FormerLurker** [comment]
Try this new branch:  https://github.com/FormerLurker/ArcWelderPlugin/archive/devel.zip

I believe I fixed the desktop notification issue.  I just removed the desktop bit from the progress, and added a separate completed desktop notification with no fallback.  That means you will get both a desktop and browser toast for the completed message if it is enabled (If I did it right, they don't show up for me for some reason, though I allowed permissions.. happens with most notifications on most sites).

Let me know if it's fixed, and thanks for posting!

**Comment by FormerLurker** [comment]
Oh, and I added notification settings for you too ;)

**Comment by FormerLurker** [comment]
This has been completed and released.  Please open a new issue if you have any problems with desktop notifications.  For some reason they just don't appear (they are not disallowed on my machine) at all for me, so I cannot test :(

Closed!

**Comment by jneilliii** [comment]
You know, I'm not sure I've seen those since installing the development package for testing either...
