### ISSUE TITLE
Support for object cancelling

### ISSUE THREAD

**Issue by girrrrrrr2** [FormerLurker/ArcWelderPlugin#32]
As far as I can tell the conversion script removes the lines that declare what part is which. 

Would it be possible to leave those lines in so that its possible to use the cancel object part of Marlin/Octoprint?

**Comment by FormerLurker** [comment]
Hmm..  Can you submit a gcode file that contains the object cancel codes?  That way I can see what they look like before and after conversion.  Thanks!

**Comment by girrrrrrr2** [comment]
here is a before and after of a project im working on.

[Coupler_Cage.zip](https://github.com/FormerLurker/ArcWelderPlugin/files/5079630/Coupler_Cage.zip)

**Comment by FormerLurker** [comment]
Excellent, this will help, thx!

**Comment by girrrrrrr2** [comment]
No problem! and if you want any more i can get you more!

**Comment by andreibobirica** [comment]
IT deletes M486 too?

**Comment by FormerLurker** [comment]
@girrrrrrr2 and @andreibobirica,

FYI, my investigation into this issue is still ongoing.  Sorry this has gotten pushed back, but I had some family stuff to deal with the last couple weeks.  I WILL get to this ASAP.

**Comment by girrrrrrr2** [comment]
> @girrrrrrr2 and @andreibobirica,
> 
> FYI, my investigation into this issue is still ongoing.  Sorry this has gotten pushed back, but I had some family stuff to deal with the last couple weeks.  I WILL get to this ASAP.

Nah you are fine take your time. I can still use it when I need it. The part cancelation thing isn't needed that often. But when it is. It's nice to have.

**Comment by FormerLurker** [comment]
I think I fixed it.  Looks like the cancel object's ```@Objectinfo``` tag was case sensitive.  I fixed the case sensitivity issue (had TONS of problems with this, lol!), and that seems to have fixed lots of other random issues.

I have NOT actually tried a print with cancel object, but looking at the plugin and the before/after gcode, I think it's working.  You can try the fix by installing v0.1.0rc1.dev5 from master as soon as I drop the release, which should be soon.  Please let me know if it's working!

**Comment by girrrrrrr2** [comment]
Ill try this weekend!

**Comment by girrrrrrr2** [comment]
So I forgot to check last weekend (Mostly because I was doing a bunch single object prints.) But it works perfect for me!

Thank you for fixing it!

**Comment by FormerLurker** [comment]
Awesome!!!!  I figured it would work, but confirmation is extremely valuable.  Thanks for that!  Closed!
