### ISSUE TITLE
Corrupt gcode after conversion

### ISSUE THREAD

**Issue by NickRno77** [FormerLurker/ArcWelderPlugin#33]
Prusa Mk3s. OctoPi 3b

I printer a part yesterday with 0.6 Nozzle Layer Height 0.3 I got corruption after AW convert, this part printed ok using a 0.4 Nozzle and Layer Height of 0.15 also AW converted. When printed withought AW conversion print looks good but stutter back.

When I viewed the gcode in ideamaker I can clearly see the corruption lines in the view, when I view the same file not converted there is no corruption?

I've attached the GCODE and photos of screengrabs and part photos
![IMG_3304](https://user-images.githubusercontent.com/61921235/90313579-996b5480-df05-11ea-94d2-477a4ab3c1fe.jpg)
![IMG_3306](https://user-images.githubusercontent.com/61921235/90313589-a25c2600-df05-11ea-9636-3a9996625390.jpg)
![IMG_3315](https://user-images.githubusercontent.com/61921235/90313594-ac7e2480-df05-11ea-9e6f-c09a50c866e7.jpg)
![Shuttle_Box_4_pieces_V2pla aw gcode](https://user-images.githubusercontent.com/61921235/90313609-c6b80280-df05-11ea-9d45-9c6c7587f86f.JPG)
![Shuttle Box 4 pieces V2pla gcode](https://user-images.githubusercontent.com/61921235/90313612-ccade380-df05-11ea-87ca-e38a88e95be5.JPG)

[ArcWelder Problem Gcode.zip](https://github.com/FormerLurker/ArcWelderPlugin/files/5078725/ArcWelder.Problem.Gcode.zip)

**Comment by FormerLurker** [comment]
I will run this through my analyzer.  Thanks for the report.

**Comment by NickRno77** [comment]
> I will run this through my analyzer. Thanks for the report.

Great thanks, I should of said ArcWelder has been great up till now although 0.6 nozzle does stutter a little, does that make sense ?

**Comment by FormerLurker** [comment]
Of course!  Bugs happen, an I am glad to find/fix them.

**Comment by FormerLurker** [comment]
OK, so I don't see the corruption when viewing in Simplify 3d.  That doesn't mean there is some issue, but in order to find it we will have to isolate which layer is having the issue.  Any way you could measure up on your print to identify the layer height from your first image where the exterior perimeter didn't print correctly?  If we can do that I'd recommend extracting that layer and only printing it to see if the problem happens again in the same spot.  Knowing exactly where the failure is would save a couple hours of manually reviewing hundreds of lines of gcode :)

![image](https://user-images.githubusercontent.com/33363128/90317708-de38c080-def0-11ea-82f2-1bcbf90dad26.png)

**Comment by NickRno77** [comment]
> OK, so I don't see the corruption when viewing in Simplify 3d. That doesn't mean there is some issue, but in order to find it we will have to isolate which layer is having the issue. Any way you could measure up on your print to identify the layer height from your first image where the exterior perimeter didn't print correctly? If we can do that I'd recommend extracting that layer and only printing it to see if the problem happens again in the same spot. Knowing exactly where the failure is would save a couple hours of manually reviewing hundreds of lines of gcode :)
> 
> ![image](https://user-images.githubusercontent.com/33363128/90317708-de38c080-def0-11ea-82f2-1bcbf90dad26.png)
 I hope this helps, its slightly above the female part of the latch, maybe 2 or 3 layers. I thought the latch projecting across the print might be something to do with the problem?
![Shuttle Box 4 pieces V2pla_layer](https://user-images.githubusercontent.com/61921235/90318485-b1a09b00-df28-11ea-8193-fa37db98f7aa.JPG)
![IMG_3316](https://user-images.githubusercontent.com/61921235/90318556-3390c400-df29-11ea-9f3c-45d090362a5e.jpg)

**Comment by FormerLurker** [comment]
Hey, since this doesn't appear to be an arcwelder issue, I'm going to go ahead and close this.  Let me know if you have any other issues!
