### ISSUE TITLE
Enhancement improve GUI

### ISSUE THREAD

**Issue by LMS0815** [FormerLurker/ArcWelderPlugin#42]
If the browser has a high horizontal resolution the main GUI configuration tab is out of order.

![image](https://user-images.githubusercontent.com/8235214/97148618-b923c200-176b-11eb-80c6-652356d566fe.png)

For my opinion we only need the statistics on that screen anyway. 
Please consider hiding and/or removing the  settings overview with an option switch on the main configuration..

**Comment by FormerLurker** [comment]
Looks like a css issue.  Would you be willing to disable your other UI plugins and see if this page looks better?  I'd like to narrow it down to a particular plugin so I can see what is causing this, and potentially fix it.  Here is what it should look like:

![image](https://user-images.githubusercontent.com/33363128/97181969-e8d1ca80-1769-11eb-91bf-07a8c4d5e445.png)

I do want to show the current run configuration, but I may add a show/hide button, and will store the state in the browser storage so it remembers.

**Comment by LMS0815** [comment]
I am sure the _issue_ it is related/cause to Themify which i am using to update the css (as you mentioned).
I like this setting as it enables OctoPrint to use the whole 16:9 screen and not only a fraction of it.

![image](https://user-images.githubusercontent.com/8235214/97184216-f81f3b00-179e-11eb-9d23-f6ece2624f17.png)

**Comment by FormerLurker** [comment]
Looks like your .span8 selector is too broad, and is affecting all span8s on the page.  Try this instead:

Selector: ```.tabbable.span8```
CSS-Rule: ```width```
Value: ```calc(100% - 300px)```

The result should be something similar to this:

![image](https://user-images.githubusercontent.com/33363128/97186298-1b31f680-176f-11eb-88b0-9376f6313020.png)

**Comment by LMS0815** [comment]
Unfortunately myscreenshot is cutting the content. The setting is `calc(95% - 360px)`

I disabled it and added your recommendation. 
100% setting is not working, But 95% did the trick.

Selector: `.tabbable.span8`
CSS-Rule: `width`
Value: `calc(95% - 300px)`

Selector: `.container`
CSS-Rule: `width`
Value: `95%`

@FormerLurker **THANK YOU**

Please consider offering an option to remove this information from this tab and only provide the statistics.

**Comment by FormerLurker** [comment]
I will add a show/hide button.  It is a reasonable request :)
