### ISSUE TITLE
Marlin SkyNet3D-V2.3.2

### ISSUE THREAD

**Issue by jjvelar** [FormerLurker/ArcWelderPlugin#48]
Hi!
Could you please add support for Marlin SkyNet3D-V2.3.2?
I know it is old but it is working quite well in my Anet A8 :-)
Thanks and best regards,

José

**Comment by FormerLurker** [comment]
Do you mean I should add your firmware to the list of supported firmware, or that you'd like arc-welder to work with your firmware?

**Comment by jjvelar** [comment]
I would like arc-welder to work with my firmware.
Thanks

José

**Comment by FormerLurker** [comment]
So, I took a look at the firmware, and you are correct:  it is really old.

> I would like arc-welder to work with my firmware.

There isn't any modification I can make to Arc Welder that will make it work with your firmware.  I looked online, and there are several guides for upgrading the Anet A8 to Marlin 2.  However, the example configuration file on [Marlin's github page](https://github.com/MarlinFirmware/Marlin/tree/2.0.x/config) has arc support disabled.  I'm not sure if the A8 has enough memory to enable that feature without further configuration changes.  Perhaps someone with an A8 and experience with Marlin 2.0 can chime in?

**Comment by jjvelar** [comment]
Not unexpected. What a pity!
Thanks for taking the time to review this.
Kind regards

José

**Comment by jjvelar** [comment]
Hi!
I just wanted you to know I have finally updated my Anet A8 to Marlin 2.0 and I have been able to activate arc support.
I am re-configuring steps and the new fancy stuff (power loss, etc) but I will start soon to "play" with arc welder.
Thanks again and best regards,
José

**Comment by FormerLurker** [comment]
Awesome!  Please let me know if it starts working!

**Comment by FormerLurker** [comment]
Going to go ahead and close this out for inactivity.  If you have any future problems, please create another issue, and thank you for your post!
