### ISSUE TITLE
Disable Arc-Welder Buttons while printing

### ISSUE THREAD

**Issue by FormerLurker** [FormerLurker/ArcWelderPlugin#50]
Disable Arc-Welder Buttons while printing, except the 'show stats' button.

**Comment by codefaux** [comment]
Related; I noticed the button to 'weld arcs' on the "Files" panel of Octoprint indicates "Cannot weld arcs during print" etc etc, but the plugin seems to have no hesitation to automatically start processing while printing, if you upload a file while printing.

Rationale;
Manual Arc-Weld trigger not available during print; sane
Automatic Arc-Weld trigger not blockable during print, always enabled; not sane

Resolutions;
Queue-but-pause automatic processing when a file is uploaded during printing?
Trip an error dialog stating that automatic processing was skipped and will need to be manually triggered?

Also, fantastic plugin. Spiral Vase stuff looks -incredible- now, it's blowing my mind. I've ALWAYS been mad that slicers seem to ignore arcs. Thank you!

**Comment by FormerLurker** [comment]
Yeah, i actually already fixed this.  It will now also cancel processing if you start a print, and will re-queue it to process after the print completes. I am testing this stuff now.

Also, thanks for your compliments!  I'm very glad you are finding it useful!

**Comment by FormerLurker** [comment]
Hey @codefaux, this fix has been implemented.  If you want to test it, you can install from this url: ```https://github.com/FormerLurker/ArcWelderPlugin/archive/1.0.1.rc1.dev1.zip```.  Please read the release notes [here](https://github.com/FormerLurker/ArcWelderPlugin/releases/tag/1.0.1.rc1.dev1)
