### ISSUE TITLE
Option to disable automatic processing while printing

### ISSUE THREAD

**Issue by geekyboi** [FormerLurker/ArcWelderPlugin#59]
Would be good if an option could be added that disabled the automatic processing while printing. I've noticed my printer starts to stutter while arc welder is doing it's thing.

**Comment by FormerLurker** [comment]
Check out the latest pre-release.  There is not an option, per se, but processing will stop if a print starts or is running.  It will continue after the print completes.  There is a feedback issue for the pre-release too, so feel free to comment there if you try it out!

**Comment by FormerLurker** [comment]
Going to go ahead and close this.  I've verified that processing will cancel and requeue while the printer is printing in the devel version.
