### ISSUE TITLE
Ender 3 with SKR Mini E3 1.2

### ISSUE THREAD

**Issue by locka99** [FormerLurker/ArcWelderPlugin#61]
As per this [discussion](https://www.reddit.com/r/octoprint/comments/jhoani/arc_welder_anyone_try_it_out/).

My experience of using the plugin with the SKR Mini E3 didn't start out too well since I thought the print was coming out blobby. 

But actually my firmware was ignoring the arc commands and just printing the infill. BigTreeTech supplies prebuilt firmware for the board on their [github page](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3). None of these prebuilt firmwares contain arc support, so in order to utilise the plugin you must build your own firmware.

Since my Ender 3 has a BL-Touch, I also need to build support G29 auto bed levelling and the firmware wouldn't fit with both options enabled. So I had to optimize the build to make the firmware use less space and those options are described below. You may or may not need these optimization depending on your need to include ABL support or some other feature.

Before proceeding read a good tutorial on installing Visual Studio code and PlatformIO.

1. `git clone https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3.git`
2. Open Visual Studio Code on the folder `BIGTREETECH-SKR-mini-E3/firmware/V1.2/Marlin-2.0.7.2-SKR-mini-E3-V1.2`
3. Edit `platformio.ini` and add the compiler optimizations below.
4. Edit `Marlin/Configuration.h` and enable the settings described below.
5. Edit `Marlin/Configuration_adv.h` and enable ARC_SUPPORT described below.
6. Hit Ctrl+Alt+B to build.
7. Copy the `.pio/build/firmware.bin` to an micro SD, insert into the printer and turn it on.

# Changes to platformio.ini

Space-optimization - Add this line under the section in `[platformio]` in `platformio.ini`. This enables compiler optimization flags that reduce the space of the binary.

```
build_flags   = ${common.build_flags} -fno-tree-scev-cprop -fno-split-wide-types -Wl,--relax -mcall-prologues -finline-limit=3
```

# Changes to be made to `Marlin/Configuration.h`:

1. Space-optimization - Comment out "#define SHOW_BOOTSCREEN"
2. Space-optimization - Comment out "#define SLIM_LCD_MENUS" (this removes some more advanced menu options)
3. For auto bed levelling uncomment "#define BLTOUCH", "AUTO_BED_LEVELING_LINEAR" (or another ABL option) and "Z_SAFE_HOMING"

# Changes to be made to `Marlin/Configuration_adv.h` 

1. Uncomment "#define ARC_SUPPORT" for arcs.

**Comment by FormerLurker** [comment]
Awesome 👍

I am currently working of a method for testing firmware support, including help files for specific printers.  Your post will be quite useful.

Can you send your printer an M115 and paste in the response?  That will help me identify the firmware fork.

**Comment by locka99** [comment]
Send: M115
Recv: FIRMWARE_NAME:Marlin 2.0.7.2 (Oct 31 2020 14:58:34) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Ender-3 EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
Recv: Cap:SERIAL_XON_XOFF:0
Recv: Cap:BINARY_FILE_TRANSFER:0
Recv: Cap:EEPROM:1
Recv: Cap:VOLUMETRIC:1
Recv: Cap:AUTOREPORT_TEMP:1
Recv: Cap:PROGRESS:0
Recv: Cap:PRINT_JOB:1
Recv: Cap:AUTOLEVEL:1
Recv: Cap:RUNOUT:0
Recv: Cap:Z_PROBE:1
Recv: Cap:LEVELING_DATA:1
Recv: Cap:BUILD_PERCENT:1
Recv: Cap:SOFTWARE_POWER:0
Recv: Cap:TOGGLE_LIGHTS:0
Recv: Cap:CASE_LIGHT_BRIGHTNESS:0
Recv: Cap:EMERGENCY_PARSER:1
Recv: Cap:PROMPT_SUPPORT:0
Recv: Cap:SDCARD:1
Recv: Cap:AUTOREPORT_SD_STATUS:0
Recv: Cap:LONG_FILENAME:1
Recv: Cap:THERMAL_PROTECTION:1
Recv: Cap:MOTION_MODES:0
Recv: Cap:ARCS:1
Recv: Cap:BABYSTEPPING:1
Recv: Cap:CHAMBER_TEMPERATURE:0
Recv: ok
Send: M155 S2
Recv: ok
Recv:  T:168.28 /0.00 B:47.11 /0.00 @:0 B@:0
Recv:  T:165.83 /0.00 B:46.38 /0.00 @:0 B@:0

**Comment by FormerLurker** [comment]
Excellent, thank you!

**Comment by FormerLurker** [comment]
So, this check isn't perfect, and there are still some things I need to fix, if you want to try it out you can install from the plugin manager by clicking 'Get More' then adding this line to the 'From Url...' box and clicking install:  ```https://github.com/FormerLurker/ArcWelderPlugin/archive/d92528cdebf158f67b906caf99c50a35c7fcbc4e.zip```

Once the install is finished, restart octoprint and make sure your printer is connected (this is one of the things that's broken).  Then go to the arc-welder tab and click on the new 'Check Firmware' button.  It is possible that a check has already completed.  

Here is what it looks like:

![image](https://user-images.githubusercontent.com/33363128/98486325-4a6e4c00-21e2-11eb-8258-8c172803a8b9.png)


If you have any problems running the checker, go to the arc welder settings and turn on verbose logging for the firmware checker like so:

![image](https://user-images.githubusercontent.com/33363128/98486206-940a6700-21e1-11eb-988e-c89a21be0873.png)

Clear the current logs:

![image](https://user-images.githubusercontent.com/33363128/98486215-a2588300-21e1-11eb-95f2-4b27abcc8b1c.png)

Save your settings changes:

![image](https://user-images.githubusercontent.com/33363128/98486258-e0ee3d80-21e1-11eb-8478-49b4c99f18c9.png)

Click on the firmware check in the Arc Welder Tab:

![image](https://user-images.githubusercontent.com/33363128/98486225-b2706280-21e1-11eb-9d91-f1099a027f30.png)

Then download and post your log file at gist.github.com.  You can download it via the Octoprint logging menu, or go to the arc welder settings and click download log:

![image](https://user-images.githubusercontent.com/33363128/98486251-d633a880-21e1-11eb-9409-ba6e2d55a8ad.png)

I've still got to add help files for various firmware versions with known issues, but for now you can just send me a snapshot of the checker and I'll let you know what your options are.

**Comment by Deses** [comment]
> Since my Ender 3 has a BL-Touch, I also need to build support G29 auto bed levelling and the firmware wouldn't fit with both options enabled. 

I have the exact same board and it has space for 512 kb firmwares... I have everything and the kitchen sink enabled without problem.

**Comment by FormerLurker** [comment]
@Deses , thanks for pointing this out!  I'm learning a lot about specific boards and firmware, and it all helps!

Also, I just dropped a new rc/devel version of ArcWelder.  Feel free to check it out.  The software update is broken for all previous versions if you are running OctoPrint 1.5+, so you'll have to install it manually.  Check out [this issue](https://github.com/FormerLurker/ArcWelderPlugin/issues/106) for details.

K, gonna close this, thanks both of you, and let me know if I should reopen.

**Comment by Deses** [comment]
Thanks for the heads up! I'll try it soon.
