### ISSUE TITLE
[Feature Request] - Before and After filesizes

### ISSUE THREAD

**Issue by KenLucke** [FormerLurker/ArcWelderPlugin#7]
Please add a Before and After Filesize (or just bytes saved) to the results dialog, for information (and dancing in the streets) purposes.

**Comment by FormerLurker** [comment]
I will add this soon.  Will update this issue once it is completed.  For now, just look in the file manager.

**Comment by FormerLurker** [comment]
How is this:

![image](https://user-images.githubusercontent.com/33363128/80427319-1a4a0600-88ad-11ea-8e10-81688ef534be.png)

I may add this to the progress display as well.

**Comment by FormerLurker** [comment]
Here is is on the progress display:

![image](https://user-images.githubusercontent.com/33363128/80429356-83337d00-88b1-11ea-879f-3a00ce8b86ad.png)

**Comment by FormerLurker** [comment]
This has been completed and released.  Closed!
