### ISSUE TITLE
Feature request - Stand Alone Mode

### ISSUE THREAD

**Issue by maxcom99** [FormerLurker/ArcWelderPlugin#73]
Any chance of running this via CLI without installing octoprint so I can leverage this for my other printers?

**Comment by FormerLurker** [comment]
Already Done.  Check the [ARcWelderLib repo here](https://github.com/FormerLurker/ArcWelderLib) and see the latest artifacts [here](https://github.com/FormerLurker/ArcWelderLib/actions/runs/352631957).  I haven't dropped this officially, so the code could change without warning.  I won't be messing with it for the next few days at least though.

Also, the console application is mentioned both on the plugin repository page at plugins.octoprint.org, in the ArcWelderPlugin wiki, and in the readme.md.  You can get help by running the ArcWelder.exe with the --help parameter.
