### ISSUE TITLE
Works fine with my Wanhao Duplicator i3 with original firmware

### ISSUE THREAD

**Issue by ghsamme** [FormerLurker/ArcWelderPlugin#74]
Saves a lot of printing time when printing from octoprint. I use default settings and haven't found any errors yet.

**Comment by FormerLurker** [comment]
Hey, can you do me a favor?  Try sending your printer an ```M115``` command via the OctoPrint terminal and paste the returned value here?  Then send it a naked ```G2``` command and see what it returns.

I'd like to see what my firmware checker says about your printer knowing that you have no issues.

Thanks!

**Comment by FormerLurker** [comment]
Going to close this out to keep the issues clean.  Feel free to post again if anything comes up!
