### ISSUE TITLE
Standalone version?

### ISSUE THREAD

**Issue by neoOpus** [FormerLurker/ArcWelderPlugin#75]
Hi, I would like to know if it's possible to have a standalone version as it will help more people fixing issues like stuttering and blobs

**Comment by FormerLurker** [comment]
There is one.  Check my ArcWelderLib repo and check out the actions tab.

That hasnt been officially released yet, but the core engine is identical to the plugin.

However, you should definitely check out octoprint if you can!

**Comment by FormerLurker** [comment]
I'm going to go ahead and close this.  Let me know if you need any help with the console app.
