### ISSUE TITLE
Test part

### ISSUE THREAD

**Issue by 5axes** [FormerLurker/ArcWelderPlugin#88]
On the Benchy boat model, is there a model that could be used as a test part to validate conversions in G02/G03 interpolation?

**Comment by FormerLurker** [comment]
Good question...  I don't have anything that is perfect for testing.  I have a couple gcode files I use for testing.  I have a spiral, a benchy sliced with Archimedean infill and have cut out the first layer, as well as a few files that caused issues in the past.

**Comment by 5axes** [comment]
This one can be used for different tests, but as I have no special issues in G1 with the sliced Gcode it's cannot be considered as a real test part.
![Test_Part-2](https://user-images.githubusercontent.com/11015345/101246345-fee08c80-3712-11eb-8f72-198622fc9da2.JPG)
Hereafter the OpenSCAD file :
[SpiraleCercle.zip](https://github.com/FormerLurker/ArcWelderPlugin/files/5647255/SpiraleCercle.zip)

**Comment by FormerLurker** [comment]
Nice!  I have a small circle scad that I just remembered (just got up.. head fog) that i will post here.

**Comment by FormerLurker** [comment]
[arc_test.zip](https://github.com/FormerLurker/ArcWelderPlugin/files/5647353/arc_test.zip)

![image](https://user-images.githubusercontent.com/33363128/101247940-f91e8300-36e1-11eb-826c-9021c2166d7f.png)

**Comment by FormerLurker** [comment]
Hey, going to close this.  The file you sent is VERY useful, thank you so much!

**Comment by 5axes** [comment]
No need to keep it open
