### ISSUE TITLE
TypeError: remove_file() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by Yoghoo** [FormerLurker/ArcWelderPlugin#90]
When processing a gcode file it fails and gives the following error in the log file:

```
2020-12-10 12:23:09,776 - arc_welder.preprocessor - ERROR - An unhandled exception occurred while preprocessing the gcode file.
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_arc_welder/preprocessor.py", line 229, in run
    self._process(task)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_arc_welder/preprocessor.py", line 326, in _process
    task, results
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_arc_welder/__init__.py", line 947, in preprocessing_success
    task, results, additional_metadata
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_arc_welder/__init__.py", line 749, in save_preprocessed_file
    self._file_manager.remove_file(target_path)
TypeError: remove_file() takes exactly 3 arguments (2 given)
 
```

This is with version 1.0.1rc1.dev2+u.2a95fab. Here are the most important settings regarding this error:

![image](https://user-images.githubusercontent.com/8544667/101766872-b397f680-3ae3-11eb-9e9d-8de23fcc99f1.png)

**Comment by Yoghoo** [comment]
Workaround for now is to disable overwrite source file:

![image](https://user-images.githubusercontent.com/8544667/101767451-839d2300-3ae4-11eb-82d9-9c07017b0a7b.png)

Then the processing is successful.

**Comment by FormerLurker** [comment]
I could have sworn this was working.  I must have somehow removed the LOCAL flag...  Will fix and push asap, thanks for the report!

**Comment by FormerLurker** [comment]
This is strange.  Take a look at the docs for that command:

![image](https://user-images.githubusercontent.com/33363128/101786978-2f824680-3ac4-11eb-87f8-0e9b5977bb41.png)

and the corresponding definition:

![image](https://user-images.githubusercontent.com/33363128/101787087-50e33280-3ac4-11eb-84ba-55de57d846df.png)

What version of OctoPrint are you using?

**Comment by Yoghoo** [comment]
OctoPrint 1.5.1
Python 2.7.16
OctoPi 0.17.0

**Comment by FormerLurker** [comment]
Ok, can you install via the plugin manager by clicking 'Get More' and pasting this link into the 'from url...' box:  https://github.com/FormerLurker/ArcWelderPlugin/archive/8754b74bb5255eb52e67bd8e04e95404bba4b61d.zip

Let me know if that helps.

**Comment by Yoghoo** [comment]
Just started another print for that other issue. Will try it after it's finished. Thanks.

**Comment by Yoghoo** [comment]
Tested the zip file and the problem seems to be solved. What did you change?

**Comment by FormerLurker** [comment]
I added the missing parameter :)  The docs I saw were referring to the storage interface, and the file manager docs were missing.  Not sure how or why, but I found the commit where I removed the storage location parameter, and I guess I never tested with overwrite after that (it's inconvenient when testing the same file over and over to have to reupload it).

**Comment by FormerLurker** [comment]
It's just one of those goofs that happen with a one man/woman show, lol.
