### ISSUE TITLE
ArcWelderPlugin prints the wrong file

### ISSUE THREAD

**Issue by Yoghoo** [FormerLurker/ArcWelderPlugin#91]
I uploaded a file from Cura to OctoPrint. It's being processed and starts to print afterwards. These are the settings for the plugin:

![image](https://user-images.githubusercontent.com/8544667/101918496-b705ad80-3bc9-11eb-93da-d74e2171f1da.png)

You can see it has created a new file:

![image](https://user-images.githubusercontent.com/8544667/101918548-c4bb3300-3bc9-11eb-90f0-2091ffedf6c4.png)

But it prints the uploaded file and not the new file created by the plugin:

![image](https://user-images.githubusercontent.com/8544667/101918612-d997c680-3bc9-11eb-885b-4edf8aa805b9.png)

**Comment by FormerLurker** [comment]
Do you have the 'print after upload' option enabled within the cura plugin by chance?  If so, disable that

**Comment by Yoghoo** [comment]
I had that option enabled indeed. I disabled it and it prints the right one now. Think it's a good idea to add that somewhere in the help section.

**Comment by FormerLurker** [comment]
I will do that.  There is a cura arc welder plugin coming out soon, fyi.
