### ISSUE TITLE
Feature Request: Start print after conversion

### ISSUE THREAD

**Issue by brheinfelder** [FormerLurker/ArcWelderPlugin#98]
I print to Octoprint directly from Cura, so I would love to see an option to automatically load and print the file after it's converted. Right now, the original file is uploaded, the print is started, and then it's converted, resulting in the original file being printed instead of the converted one. I'm no programmer, but I think the easiest way to implement this is for the user to disable the "start print" option in Cura, and then just have an arc welder option to start the print after the file is converted.

**Comment by o-nix** [comment]
@Futureless671 already implemented in `dev` version https://github.com/FormerLurker/ArcWelderPlugin/issues/46#issuecomment-717655793

**Comment by brheinfelder** [comment]
Ah, my bad. Thanks!
